ARG BAY_IMAGE_VERSION
ARG ES_TPL

FROM "ghcr.io/dpc-sdp/bay/elasticsearch:${BAY_IMAGE_VERSION}"

ENV ES_TPL=${ES_TPL:-elasticsearch.yml}

COPY .docker/elasticsearch.yml .docker/elasticsearch.* /tmp/elasticsearch/

RUN mkdir -p config \
    && cp /tmp/elasticsearch/$ES_TPL config/elasticsearch.yml

ENV ES_JAVA_OPTS "-Xms1000m -Xmx1000m"
