# @see https://github.com/dpc-sdp/bay/blob/master/bay/images/Dockerfile.nginx
ARG BAY_IMAGE_VERSION
ARG CLI_IMAGE
FROM ${CLI_IMAGE:-cli} as cli

FROM "ghcr.io/dpc-sdp/bay/nginx:${BAY_IMAGE_VERSION}"

ENV WEBROOT=docroot

COPY --from=cli /app /app
